# .goreleaser.yaml

version: 2
pro: true

includes:
  - from_file:
      path: ./.goreleaser.yaml

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum
    output: true

homebrew_casks:
  - name: cli
    binary: permguard
    ids: ["permguard_cli"]
    repository:
      owner: "{{ .Env.ORG }}"
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    alternative_names:
      - cli@{{ .Version }}
      - cli@{{ .Major }}
    homepage: "https://community.permguard.com/"
    description: "Permguard CLI"
    commit_author:
      name: Permguard Team
      email: opensource@permguard.com
    license: "Apache-2.0"
    url:
      template: "https://github.com/permguard/permguard/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: "github.com/permguard/permguard/"
    skip_upload: false
