# .goreleaser.yaml

version: 2

env:
  - PROJECT_PATH=github.com/permguard/permguard

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: permguard_cli
    dir: "./cmd/cli"
    binary: "permguard"
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X {{ .Env.PROJECT_PATH }}/internal/cli/common.Version={{ .Version }}
      - -X {{ .Env.PROJECT_PATH }}/internal/cli/common.BuildTime={{ .Timestamp }}
      - -X {{ .Env.PROJECT_PATH }}/internal/cli/common.GitCommit={{ .Commit }}


  - id: permguard_all_in_one_linux
    dir: "./cmd/server-all-in-one"
    binary: "server-all-in-one"
    goos: [linux]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X {{ .Env.PROJECT_PATH }}/internal/agents/cli.Version={{ .Version }}
      - -X {{ .Env.PROJECT_PATH }}/internal/agents/cli.BuildTime={{ .Timestamp }}
      - -X {{ .Env.PROJECT_PATH }}/internal/agents/cli.GitCommit={{ .Commit }}

  - id: permguard_all_in_one_windows
    dir: "./cmd/server-all-in-one"
    binary: "server-all-in-one"
    goos: [windows]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X {{ .Env.PROJECT_PATH }}/internal/agents/cli.Version={{ .Version }}
      - -X {{ .Env.PROJECT_PATH }}/internal/agents/cli.BuildTime={{ .Timestamp }}
      - -X {{ .Env.PROJECT_PATH }}/internal/agents/cli.GitCommit={{ .Commit }}

  - id: permguard_all_in_one_darwin
    dir: "./cmd/server-all-in-one"
    binary: "server-all-in-one"
    goos: [darwin]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X {{ .Env.PROJECT_PATH }}/internal/agents/cli.Version={{ .Version }}
      - -X {{ .Env.PROJECT_PATH }}/internal/agents/cli.BuildTime={{ .Timestamp }}
      - -X {{ .Env.PROJECT_PATH }}/internal/agents/cli.GitCommit={{ .Commit }}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Binary }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
  - formats: [tar.gz]
    id: permguard_all_in_one
    ids: ["permguard_all_in_one_linux", "permguard_all_in_one_windows", "permguard_all_in_one_darwin"]
    name_template: >-
      {{ .ProjectName }}_{{ .Binary }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]


dockers:
  # amd64
  - id: aio_amd64
    use: buildx
    ids: [permguard_all_in_one_linux]                       # collega il build sopra
    goos: linux
    goarch: amd64
    image_templates:
      - permguard/all-in-one:{{ .Version }}-amd64
    dockerfile: ./cmd/server-all-in-one/Dockerfile # è nella sua cartella
    skip_push: false
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title=permguard-all-in-one"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.source={{ .Env.PROJECT_PATH }}"
    # se il Dockerfile usa ARG per il binario:
    # - "--build-arg=BINARY={{ .Binary }}"

  # arm64
  - id: aio_arm64
    use: buildx
    ids: [permguard_all_in_one_linux]
    goos: linux
    goarch: arm64
    image_templates:
      - permguard/all-in-one:{{ .Version }}-arm64
    dockerfile: ./cmd/server-all-in-one/Dockerfile
    skip_push: false
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.title=permguard-all-in-one"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.source={{ .Env.PROJECT_PATH }}"
    # - "--build-arg=BINARY={{ .Binary }}"

docker_manifests:
  - name_template: permguard/all-in-one:{{ .Version }}
    image_templates:
      - permguard/all-in-one:{{ .Version }}-amd64
      - permguard/all-in-one:{{ .Version }}-arm64
  - name_template: permguard/all-in-one:latest
    image_templates:
      - permguard/all-in-one:{{ .Version }}-amd64
      - permguard/all-in-one:{{ .Version }}-arm64
  - name_template: permguard/all-in-one:{{ .Major }}
    image_templates:
      - permguard/all-in-one:{{ .Version }}-amd64
      - permguard/all-in-one:{{ .Version }}-arm64
  - name_template: permguard/all-in-one:{{ .Major }}.{{ .Minor }}
    image_templates:
      - permguard/all-in-one:{{ .Version }}-amd64
      - permguard/all-in-one:{{ .Version }}-arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
