{{/*
Copyright (c) 2022 Nitro Agility S.r.l.
SPDX-License-Identifier: Apache-2.0
*/}}
{{- range $component, $plane := dict "control-plane" .Values.controlPlane "data-plane" .Values.dataPlane }}
{{- if and $plane.enabled $plane.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "permguard.fullname" $ }}-{{ $component }}
  labels:
    {{- include "permguard.componentLabels" (dict "root" $ "component" $component) | nindent 4 }}
spec:
  minAvailable: {{ $plane.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "permguard.selectorLabels" (dict "root" $ "component" $component) | nindent 6 }}
---
{{- end }}
{{- end }}
