{{/*
Copyright (c) 2022 Nitro Agility S.r.l.
SPDX-License-Identifier: Apache-2.0
*/}}
{{- range $component, $plane := dict "control-plane" .Values.controlPlane "data-plane" .Values.dataPlane }}
{{- if and $plane.enabled (include "permguard.persists" (dict "root" $ "plane" $plane)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "permguard.fullname" $ }}-{{ $component }}
  labels:
    {{- include "permguard.componentLabels" (dict "root" $ "component" $component) | nindent 4 }}
spec:
  accessModes:
    {{- toYaml $.Values.persistence.accessModes | nindent 4 }}
  {{- with $.Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size }}
---
{{- end }}
{{- end }}
{{- if and .Values.allInOne.enabled (include "permguard.persists" (dict "root" . "plane" .Values.allInOne)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "permguard.fullname" . }}-all-in-one
  labels:
    {{- include "permguard.componentLabels" (dict "root" . "component" "all-in-one") | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
