{{/*
Copyright (c) 2022 Nitro Agility S.r.l.
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.metrics.serviceMonitor.enabled }}
{{- range $component, $plane := dict "control-plane" .Values.controlPlane "data-plane" .Values.dataPlane }}
{{- if $plane.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "permguard.fullname" $ }}-{{ $component }}
  labels:
    {{- include "permguard.componentLabels" (dict "root" $ "component" $component) | nindent 4 }}
    {{- with $.Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "permguard.selectorLabels" (dict "root" $ "component" $component) | nindent 6 }}
  endpoints:
    - port: telemetry
      path: /metrics
      interval: {{ $.Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ $.Values.metrics.serviceMonitor.scrapeTimeout }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
---
{{- end }}
{{- end }}
{{- end }}
