// Copyright 2025 Nitro Agility S.r.l.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/agents/services/pdp/endpoints/api/v1/pdp.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PolicyStore is the location where policies are maintained.
type PolicyStore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=Kind,proto3" json:"Kind,omitempty"`
	ID            string                 `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyStore) Reset() {
	*x = PolicyStore{}
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyStore) ProtoMessage() {}

func (x *PolicyStore) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyStore.ProtoReflect.Descriptor instead.
func (*PolicyStore) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyStore) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PolicyStore) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

// Principal represents the entity making the request.
type Principal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	ID            string                 `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Source        *string                `protobuf:"bytes,3,opt,name=Source,proto3,oneof" json:"Source,omitempty"`
	IdentityToken *string                `protobuf:"bytes,4,opt,name=IdentityToken,proto3,oneof" json:"IdentityToken,omitempty"`
	AccessToken   *string                `protobuf:"bytes,5,opt,name=AccessToken,proto3,oneof" json:"AccessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{1}
}

func (x *Principal) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Principal) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Principal) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *Principal) GetIdentityToken() string {
	if x != nil && x.IdentityToken != nil {
		return *x.IdentityToken
	}
	return ""
}

func (x *Principal) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

// Entities represent the entities provided in the context for the authorization decision.
type Entities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=Schema,proto3" json:"Schema,omitempty"`
	Items         []*structpb.Struct     `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entities) Reset() {
	*x = Entities{}
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entities) ProtoMessage() {}

func (x *Entities) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entities.ProtoReflect.Descriptor instead.
func (*Entities) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{2}
}

func (x *Entities) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Entities) GetItems() []*structpb.Struct {
	if x != nil {
		return x.Items
	}
	return nil
}

// Subject is the entity on which the authorization decision is made.
type Subject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	ID            string                 `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Source        *string                `protobuf:"bytes,3,opt,name=Source,proto3,oneof" json:"Source,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,4,opt,name=Properties,proto3,oneof" json:"Properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{3}
}

func (x *Subject) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Subject) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Subject) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *Subject) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

// Resource is the entity on which the authorization decision is made.
type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	ID            string                 `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,3,opt,name=Properties,proto3,oneof" json:"Properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{4}
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Resource) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

// Action is the operation on which the authorization decision is made.
type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,2,opt,name=Properties,proto3,oneof" json:"Properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{5}
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

// AuthorizationModelRequest is the input context for making the authorization decision.
type AuthorizationModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneID        int64                  `protobuf:"varint,1,opt,name=ZoneID,proto3" json:"ZoneID,omitempty"`
	PolicyStore   *PolicyStore           `protobuf:"bytes,2,opt,name=PolicyStore,proto3" json:"PolicyStore,omitempty"`
	Principal     *Principal             `protobuf:"bytes,3,opt,name=Principal,proto3,oneof" json:"Principal,omitempty"`
	Entities      *Entities              `protobuf:"bytes,4,opt,name=Entities,proto3,oneof" json:"Entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationModelRequest) Reset() {
	*x = AuthorizationModelRequest{}
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationModelRequest) ProtoMessage() {}

func (x *AuthorizationModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationModelRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationModelRequest) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{6}
}

func (x *AuthorizationModelRequest) GetZoneID() int64 {
	if x != nil {
		return x.ZoneID
	}
	return 0
}

func (x *AuthorizationModelRequest) GetPolicyStore() *PolicyStore {
	if x != nil {
		return x.PolicyStore
	}
	return nil
}

func (x *AuthorizationModelRequest) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *AuthorizationModelRequest) GetEntities() *Entities {
	if x != nil {
		return x.Entities
	}
	return nil
}

// EvaluationRequest represents the request to evaluate the authorization decision.
type EvaluationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestID     *string                `protobuf:"bytes,1,opt,name=RequestID,proto3,oneof" json:"RequestID,omitempty"`
	Subject       *Subject               `protobuf:"bytes,2,opt,name=Subject,proto3,oneof" json:"Subject,omitempty"`
	Resource      *Resource              `protobuf:"bytes,3,opt,name=Resource,proto3,oneof" json:"Resource,omitempty"`
	Action        *Action                `protobuf:"bytes,4,opt,name=Action,proto3,oneof" json:"Action,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,5,opt,name=Context,proto3,oneof" json:"Context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationRequest) Reset() {
	*x = EvaluationRequest{}
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationRequest) ProtoMessage() {}

func (x *EvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationRequest.ProtoReflect.Descriptor instead.
func (*EvaluationRequest) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{7}
}

func (x *EvaluationRequest) GetRequestID() string {
	if x != nil && x.RequestID != nil {
		return *x.RequestID
	}
	return ""
}

func (x *EvaluationRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *EvaluationRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *EvaluationRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *EvaluationRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

// AuthorizationCheckRequest represents the request to perform an authorization decision.
type AuthorizationCheckRequest struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	AuthorizationModel *AuthorizationModelRequest `protobuf:"bytes,1,opt,name=AuthorizationModel,proto3" json:"AuthorizationModel,omitempty"`
	RequestID          *string                    `protobuf:"bytes,2,opt,name=RequestID,proto3,oneof" json:"RequestID,omitempty"`
	Subject            *Subject                   `protobuf:"bytes,3,opt,name=Subject,proto3,oneof" json:"Subject,omitempty"`
	Resource           *Resource                  `protobuf:"bytes,4,opt,name=Resource,proto3,oneof" json:"Resource,omitempty"`
	Action             *Action                    `protobuf:"bytes,5,opt,name=Action,proto3,oneof" json:"Action,omitempty"`
	Context            *structpb.Struct           `protobuf:"bytes,6,opt,name=Context,proto3,oneof" json:"Context,omitempty"`
	Evaluations        []*EvaluationRequest       `protobuf:"bytes,7,rep,name=Evaluations,proto3" json:"Evaluations,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AuthorizationCheckRequest) Reset() {
	*x = AuthorizationCheckRequest{}
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationCheckRequest) ProtoMessage() {}

func (x *AuthorizationCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationCheckRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{8}
}

func (x *AuthorizationCheckRequest) GetAuthorizationModel() *AuthorizationModelRequest {
	if x != nil {
		return x.AuthorizationModel
	}
	return nil
}

func (x *AuthorizationCheckRequest) GetRequestID() string {
	if x != nil && x.RequestID != nil {
		return *x.RequestID
	}
	return ""
}

func (x *AuthorizationCheckRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *AuthorizationCheckRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *AuthorizationCheckRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *AuthorizationCheckRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *AuthorizationCheckRequest) GetEvaluations() []*EvaluationRequest {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

// ReasonResponse provides the rationale for the response.
type ReasonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasonResponse) Reset() {
	*x = ReasonResponse{}
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasonResponse) ProtoMessage() {}

func (x *ReasonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasonResponse.ProtoReflect.Descriptor instead.
func (*ReasonResponse) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{9}
}

func (x *ReasonResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReasonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ContextResponse represents the context included in the response.
type ContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ReasonAdmin   *ReasonResponse        `protobuf:"bytes,2,opt,name=ReasonAdmin,proto3" json:"ReasonAdmin,omitempty"`
	ReasonUser    *ReasonResponse        `protobuf:"bytes,3,opt,name=ReasonUser,proto3" json:"ReasonUser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextResponse) Reset() {
	*x = ContextResponse{}
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextResponse) ProtoMessage() {}

func (x *ContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextResponse.ProtoReflect.Descriptor instead.
func (*ContextResponse) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{10}
}

func (x *ContextResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ContextResponse) GetReasonAdmin() *ReasonResponse {
	if x != nil {
		return x.ReasonAdmin
	}
	return nil
}

func (x *ContextResponse) GetReasonUser() *ReasonResponse {
	if x != nil {
		return x.ReasonUser
	}
	return nil
}

// EvaluationResponse represents the result of the evaluation process.
type EvaluationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      bool                   `protobuf:"varint,1,opt,name=Decision,proto3" json:"Decision,omitempty"`
	RequestID     *string                `protobuf:"bytes,2,opt,name=RequestID,proto3,oneof" json:"RequestID,omitempty"`
	Context       *ContextResponse       `protobuf:"bytes,3,opt,name=Context,proto3,oneof" json:"Context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationResponse) Reset() {
	*x = EvaluationResponse{}
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationResponse) ProtoMessage() {}

func (x *EvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationResponse.ProtoReflect.Descriptor instead.
func (*EvaluationResponse) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{11}
}

func (x *EvaluationResponse) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

func (x *EvaluationResponse) GetRequestID() string {
	if x != nil && x.RequestID != nil {
		return *x.RequestID
	}
	return ""
}

func (x *EvaluationResponse) GetContext() *ContextResponse {
	if x != nil {
		return x.Context
	}
	return nil
}

// AuthorizationCheckResponse represents the outcome of the authorization decision.
type AuthorizationCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      bool                   `protobuf:"varint,1,opt,name=Decision,proto3" json:"Decision,omitempty"`
	RequestID     *string                `protobuf:"bytes,2,opt,name=RequestID,proto3,oneof" json:"RequestID,omitempty"`
	Context       *ContextResponse       `protobuf:"bytes,3,opt,name=Context,proto3,oneof" json:"Context,omitempty"`
	Evaluations   []*EvaluationResponse  `protobuf:"bytes,4,rep,name=Evaluations,proto3" json:"Evaluations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationCheckResponse) Reset() {
	*x = AuthorizationCheckResponse{}
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationCheckResponse) ProtoMessage() {}

func (x *AuthorizationCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationCheckResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{12}
}

func (x *AuthorizationCheckResponse) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

func (x *AuthorizationCheckResponse) GetRequestID() string {
	if x != nil && x.RequestID != nil {
		return *x.RequestID
	}
	return ""
}

func (x *AuthorizationCheckResponse) GetContext() *ContextResponse {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *AuthorizationCheckResponse) GetEvaluations() []*EvaluationResponse {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

var File_internal_agents_services_pdp_endpoints_api_v1_pdp_proto protoreflect.FileDescriptor

const file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDesc = "" +
	"\n" +
	"7internal/agents/services/pdp/endpoints/api/v1/pdp.proto\x12\x13policydecisionpoint\x1a\x1cgoogle/protobuf/struct.proto\"1\n" +
	"\vPolicyStore\x12\x12\n" +
	"\x04Kind\x18\x01 \x01(\tR\x04Kind\x12\x0e\n" +
	"\x02ID\x18\x02 \x01(\tR\x02ID\"\xcb\x01\n" +
	"\tPrincipal\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x12\x0e\n" +
	"\x02ID\x18\x02 \x01(\tR\x02ID\x12\x1b\n" +
	"\x06Source\x18\x03 \x01(\tH\x00R\x06Source\x88\x01\x01\x12)\n" +
	"\rIdentityToken\x18\x04 \x01(\tH\x01R\rIdentityToken\x88\x01\x01\x12%\n" +
	"\vAccessToken\x18\x05 \x01(\tH\x02R\vAccessToken\x88\x01\x01B\t\n" +
	"\a_SourceB\x10\n" +
	"\x0e_IdentityTokenB\x0e\n" +
	"\f_AccessToken\"Q\n" +
	"\bEntities\x12\x16\n" +
	"\x06Schema\x18\x01 \x01(\tR\x06Schema\x12-\n" +
	"\x05Items\x18\x02 \x03(\v2\x17.google.protobuf.StructR\x05Items\"\xa2\x01\n" +
	"\aSubject\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x12\x0e\n" +
	"\x02ID\x18\x02 \x01(\tR\x02ID\x12\x1b\n" +
	"\x06Source\x18\x03 \x01(\tH\x00R\x06Source\x88\x01\x01\x12<\n" +
	"\n" +
	"Properties\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x01R\n" +
	"Properties\x88\x01\x01B\t\n" +
	"\a_SourceB\r\n" +
	"\v_Properties\"{\n" +
	"\bResource\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x12\x0e\n" +
	"\x02ID\x18\x02 \x01(\tR\x02ID\x12<\n" +
	"\n" +
	"Properties\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x00R\n" +
	"Properties\x88\x01\x01B\r\n" +
	"\v_Properties\"i\n" +
	"\x06Action\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12<\n" +
	"\n" +
	"Properties\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x00R\n" +
	"Properties\x88\x01\x01B\r\n" +
	"\v_Properties\"\x95\x02\n" +
	"\x19AuthorizationModelRequest\x12\x16\n" +
	"\x06ZoneID\x18\x01 \x01(\x03R\x06ZoneID\x12B\n" +
	"\vPolicyStore\x18\x02 \x01(\v2 .policydecisionpoint.PolicyStoreR\vPolicyStore\x12A\n" +
	"\tPrincipal\x18\x03 \x01(\v2\x1e.policydecisionpoint.PrincipalH\x00R\tPrincipal\x88\x01\x01\x12>\n" +
	"\bEntities\x18\x04 \x01(\v2\x1d.policydecisionpoint.EntitiesH\x01R\bEntities\x88\x01\x01B\f\n" +
	"\n" +
	"_PrincipalB\v\n" +
	"\t_Entities\"\xe3\x02\n" +
	"\x11EvaluationRequest\x12!\n" +
	"\tRequestID\x18\x01 \x01(\tH\x00R\tRequestID\x88\x01\x01\x12;\n" +
	"\aSubject\x18\x02 \x01(\v2\x1c.policydecisionpoint.SubjectH\x01R\aSubject\x88\x01\x01\x12>\n" +
	"\bResource\x18\x03 \x01(\v2\x1d.policydecisionpoint.ResourceH\x02R\bResource\x88\x01\x01\x128\n" +
	"\x06Action\x18\x04 \x01(\v2\x1b.policydecisionpoint.ActionH\x03R\x06Action\x88\x01\x01\x126\n" +
	"\aContext\x18\x05 \x01(\v2\x17.google.protobuf.StructH\x04R\aContext\x88\x01\x01B\f\n" +
	"\n" +
	"_RequestIDB\n" +
	"\n" +
	"\b_SubjectB\v\n" +
	"\t_ResourceB\t\n" +
	"\a_ActionB\n" +
	"\n" +
	"\b_Context\"\x95\x04\n" +
	"\x19AuthorizationCheckRequest\x12^\n" +
	"\x12AuthorizationModel\x18\x01 \x01(\v2..policydecisionpoint.AuthorizationModelRequestR\x12AuthorizationModel\x12!\n" +
	"\tRequestID\x18\x02 \x01(\tH\x00R\tRequestID\x88\x01\x01\x12;\n" +
	"\aSubject\x18\x03 \x01(\v2\x1c.policydecisionpoint.SubjectH\x01R\aSubject\x88\x01\x01\x12>\n" +
	"\bResource\x18\x04 \x01(\v2\x1d.policydecisionpoint.ResourceH\x02R\bResource\x88\x01\x01\x128\n" +
	"\x06Action\x18\x05 \x01(\v2\x1b.policydecisionpoint.ActionH\x03R\x06Action\x88\x01\x01\x126\n" +
	"\aContext\x18\x06 \x01(\v2\x17.google.protobuf.StructH\x04R\aContext\x88\x01\x01\x12H\n" +
	"\vEvaluations\x18\a \x03(\v2&.policydecisionpoint.EvaluationRequestR\vEvaluationsB\f\n" +
	"\n" +
	"_RequestIDB\n" +
	"\n" +
	"\b_SubjectB\v\n" +
	"\t_ResourceB\t\n" +
	"\a_ActionB\n" +
	"\n" +
	"\b_Context\">\n" +
	"\x0eReasonResponse\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\tR\x04Code\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\"\xad\x01\n" +
	"\x0fContextResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12E\n" +
	"\vReasonAdmin\x18\x02 \x01(\v2#.policydecisionpoint.ReasonResponseR\vReasonAdmin\x12C\n" +
	"\n" +
	"ReasonUser\x18\x03 \x01(\v2#.policydecisionpoint.ReasonResponseR\n" +
	"ReasonUser\"\xb2\x01\n" +
	"\x12EvaluationResponse\x12\x1a\n" +
	"\bDecision\x18\x01 \x01(\bR\bDecision\x12!\n" +
	"\tRequestID\x18\x02 \x01(\tH\x00R\tRequestID\x88\x01\x01\x12C\n" +
	"\aContext\x18\x03 \x01(\v2$.policydecisionpoint.ContextResponseH\x01R\aContext\x88\x01\x01B\f\n" +
	"\n" +
	"_RequestIDB\n" +
	"\n" +
	"\b_Context\"\x85\x02\n" +
	"\x1aAuthorizationCheckResponse\x12\x1a\n" +
	"\bDecision\x18\x01 \x01(\bR\bDecision\x12!\n" +
	"\tRequestID\x18\x02 \x01(\tH\x00R\tRequestID\x88\x01\x01\x12C\n" +
	"\aContext\x18\x03 \x01(\v2$.policydecisionpoint.ContextResponseH\x01R\aContext\x88\x01\x01\x12I\n" +
	"\vEvaluations\x18\x04 \x03(\v2'.policydecisionpoint.EvaluationResponseR\vEvaluationsB\f\n" +
	"\n" +
	"_RequestIDB\n" +
	"\n" +
	"\b_Context2\x87\x01\n" +
	"\fV1PDPService\x12w\n" +
	"\x12AuthorizationCheck\x12..policydecisionpoint.AuthorizationCheckRequest\x1a/.policydecisionpoint.AuthorizationCheckResponse\"\x00B:Z8github.com/permguard/permguard/internal/hosts/api/pdp/v1b\x06proto3"

var (
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescOnce sync.Once
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescData []byte
)

func file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP() []byte {
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescOnce.Do(func() {
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDesc), len(file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDesc)))
	})
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescData
}

var file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_goTypes = []any{
	(*PolicyStore)(nil),                // 0: policydecisionpoint.PolicyStore
	(*Principal)(nil),                  // 1: policydecisionpoint.Principal
	(*Entities)(nil),                   // 2: policydecisionpoint.Entities
	(*Subject)(nil),                    // 3: policydecisionpoint.Subject
	(*Resource)(nil),                   // 4: policydecisionpoint.Resource
	(*Action)(nil),                     // 5: policydecisionpoint.Action
	(*AuthorizationModelRequest)(nil),  // 6: policydecisionpoint.AuthorizationModelRequest
	(*EvaluationRequest)(nil),          // 7: policydecisionpoint.EvaluationRequest
	(*AuthorizationCheckRequest)(nil),  // 8: policydecisionpoint.AuthorizationCheckRequest
	(*ReasonResponse)(nil),             // 9: policydecisionpoint.ReasonResponse
	(*ContextResponse)(nil),            // 10: policydecisionpoint.ContextResponse
	(*EvaluationResponse)(nil),         // 11: policydecisionpoint.EvaluationResponse
	(*AuthorizationCheckResponse)(nil), // 12: policydecisionpoint.AuthorizationCheckResponse
	(*structpb.Struct)(nil),            // 13: google.protobuf.Struct
}
var file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_depIdxs = []int32{
	13, // 0: policydecisionpoint.Entities.Items:type_name -> google.protobuf.Struct
	13, // 1: policydecisionpoint.Subject.Properties:type_name -> google.protobuf.Struct
	13, // 2: policydecisionpoint.Resource.Properties:type_name -> google.protobuf.Struct
	13, // 3: policydecisionpoint.Action.Properties:type_name -> google.protobuf.Struct
	0,  // 4: policydecisionpoint.AuthorizationModelRequest.PolicyStore:type_name -> policydecisionpoint.PolicyStore
	1,  // 5: policydecisionpoint.AuthorizationModelRequest.Principal:type_name -> policydecisionpoint.Principal
	2,  // 6: policydecisionpoint.AuthorizationModelRequest.Entities:type_name -> policydecisionpoint.Entities
	3,  // 7: policydecisionpoint.EvaluationRequest.Subject:type_name -> policydecisionpoint.Subject
	4,  // 8: policydecisionpoint.EvaluationRequest.Resource:type_name -> policydecisionpoint.Resource
	5,  // 9: policydecisionpoint.EvaluationRequest.Action:type_name -> policydecisionpoint.Action
	13, // 10: policydecisionpoint.EvaluationRequest.Context:type_name -> google.protobuf.Struct
	6,  // 11: policydecisionpoint.AuthorizationCheckRequest.AuthorizationModel:type_name -> policydecisionpoint.AuthorizationModelRequest
	3,  // 12: policydecisionpoint.AuthorizationCheckRequest.Subject:type_name -> policydecisionpoint.Subject
	4,  // 13: policydecisionpoint.AuthorizationCheckRequest.Resource:type_name -> policydecisionpoint.Resource
	5,  // 14: policydecisionpoint.AuthorizationCheckRequest.Action:type_name -> policydecisionpoint.Action
	13, // 15: policydecisionpoint.AuthorizationCheckRequest.Context:type_name -> google.protobuf.Struct
	7,  // 16: policydecisionpoint.AuthorizationCheckRequest.Evaluations:type_name -> policydecisionpoint.EvaluationRequest
	9,  // 17: policydecisionpoint.ContextResponse.ReasonAdmin:type_name -> policydecisionpoint.ReasonResponse
	9,  // 18: policydecisionpoint.ContextResponse.ReasonUser:type_name -> policydecisionpoint.ReasonResponse
	10, // 19: policydecisionpoint.EvaluationResponse.Context:type_name -> policydecisionpoint.ContextResponse
	10, // 20: policydecisionpoint.AuthorizationCheckResponse.Context:type_name -> policydecisionpoint.ContextResponse
	11, // 21: policydecisionpoint.AuthorizationCheckResponse.Evaluations:type_name -> policydecisionpoint.EvaluationResponse
	8,  // 22: policydecisionpoint.V1PDPService.AuthorizationCheck:input_type -> policydecisionpoint.AuthorizationCheckRequest
	12, // 23: policydecisionpoint.V1PDPService.AuthorizationCheck:output_type -> policydecisionpoint.AuthorizationCheckResponse
	23, // [23:24] is the sub-list for method output_type
	22, // [22:23] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_init() }
func file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_init() {
	if File_internal_agents_services_pdp_endpoints_api_v1_pdp_proto != nil {
		return
	}
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[1].OneofWrappers = []any{}
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[3].OneofWrappers = []any{}
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[4].OneofWrappers = []any{}
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[5].OneofWrappers = []any{}
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[6].OneofWrappers = []any{}
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[7].OneofWrappers = []any{}
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[8].OneofWrappers = []any{}
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[11].OneofWrappers = []any{}
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDesc), len(file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_goTypes,
		DependencyIndexes: file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_depIdxs,
		MessageInfos:      file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes,
	}.Build()
	File_internal_agents_services_pdp_endpoints_api_v1_pdp_proto = out.File
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_goTypes = nil
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_depIdxs = nil
}
