// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.2
// source: internal/agents/services/pdp/endpoints/api/v1/pdp.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VirtualState_VirtualStateView int32

const (
	VirtualState_COMBINED   VirtualState_VirtualStateView = 0
	VirtualState_UNCOMBINED VirtualState_VirtualStateView = 1
)

// Enum value maps for VirtualState_VirtualStateView.
var (
	VirtualState_VirtualStateView_name = map[int32]string{
		0: "COMBINED",
		1: "UNCOMBINED",
	}
	VirtualState_VirtualStateView_value = map[string]int32{
		"COMBINED":   0,
		"UNCOMBINED": 1,
	}
)

func (x VirtualState_VirtualStateView) Enum() *VirtualState_VirtualStateView {
	p := new(VirtualState_VirtualStateView)
	*p = x
	return p
}

func (x VirtualState_VirtualStateView) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VirtualState_VirtualStateView) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_enumTypes[0].Descriptor()
}

func (VirtualState_VirtualStateView) Type() protoreflect.EnumType {
	return &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_enumTypes[0]
}

func (x VirtualState_VirtualStateView) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VirtualState_VirtualStateView.Descriptor instead.
func (VirtualState_VirtualStateView) EnumDescriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{2, 0}
}

type Attribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{0}
}

func (x *Attribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Attribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Identity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uur        string       `protobuf:"bytes,1,opt,name=uur,proto3" json:"uur,omitempty"`
	Attributes []*Attribute `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *Identity) Reset() {
	*x = Identity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{1}
}

func (x *Identity) GetUur() string {
	if x != nil {
		return x.Uur
	}
	return ""
}

func (x *Identity) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type VirtualState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool                          `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	View    VirtualState_VirtualStateView `protobuf:"varint,2,opt,name=view,proto3,enum=policydecisionpoint.VirtualState_VirtualStateView" json:"view,omitempty"`
}

func (x *VirtualState) Reset() {
	*x = VirtualState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualState) ProtoMessage() {}

func (x *VirtualState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualState.ProtoReflect.Descriptor instead.
func (*VirtualState) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{2}
}

func (x *VirtualState) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *VirtualState) GetView() VirtualState_VirtualStateView {
	if x != nil {
		return x.View
	}
	return VirtualState_COMBINED
}

type PermissionsEngine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VirtualState *VirtualState `protobuf:"bytes,1,opt,name=virtualState,proto3" json:"virtualState,omitempty"`
}

func (x *PermissionsEngine) Reset() {
	*x = PermissionsEngine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionsEngine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsEngine) ProtoMessage() {}

func (x *PermissionsEngine) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsEngine.ProtoReflect.Descriptor instead.
func (*PermissionsEngine) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{3}
}

func (x *PermissionsEngine) GetVirtualState() *VirtualState {
	if x != nil {
		return x.VirtualState
	}
	return nil
}

type PermissionsStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PermissionsEngine *PermissionsEngine `protobuf:"bytes,1,opt,name=permissionsEngine,proto3,oneof" json:"permissionsEngine,omitempty"`
	Identity          *Identity          `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
}

func (x *PermissionsStateRequest) Reset() {
	*x = PermissionsStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionsStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsStateRequest) ProtoMessage() {}

func (x *PermissionsStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsStateRequest.ProtoReflect.Descriptor instead.
func (*PermissionsStateRequest) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{4}
}

func (x *PermissionsStateRequest) GetPermissionsEngine() *PermissionsEngine {
	if x != nil {
		return x.PermissionsEngine
	}
	return nil
}

func (x *PermissionsStateRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type ACPolicyStatement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Actions   []string `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	Resources []string `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *ACPolicyStatement) Reset() {
	*x = ACPolicyStatement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ACPolicyStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACPolicyStatement) ProtoMessage() {}

func (x *ACPolicyStatement) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACPolicyStatement.ProtoReflect.Descriptor instead.
func (*ACPolicyStatement) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{5}
}

func (x *ACPolicyStatement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ACPolicyStatement) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ACPolicyStatement) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ACPolicyStatementWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statement      *ACPolicyStatement `protobuf:"bytes,1,opt,name=statement,proto3" json:"statement,omitempty"`
	StatmentHashed string             `protobuf:"bytes,2,opt,name=statmentHashed,proto3" json:"statmentHashed,omitempty"`
}

func (x *ACPolicyStatementWrapper) Reset() {
	*x = ACPolicyStatementWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ACPolicyStatementWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACPolicyStatementWrapper) ProtoMessage() {}

func (x *ACPolicyStatementWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACPolicyStatementWrapper.ProtoReflect.Descriptor instead.
func (*ACPolicyStatementWrapper) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{6}
}

func (x *ACPolicyStatementWrapper) GetStatement() *ACPolicyStatement {
	if x != nil {
		return x.Statement
	}
	return nil
}

func (x *ACPolicyStatementWrapper) GetStatmentHashed() string {
	if x != nil {
		return x.StatmentHashed
	}
	return ""
}

type ACPermissions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Forbid []*ACPolicyStatementWrapper `protobuf:"bytes,1,rep,name=forbid,proto3" json:"forbid,omitempty"`
	Permit []*ACPolicyStatementWrapper `protobuf:"bytes,2,rep,name=permit,proto3" json:"permit,omitempty"`
}

func (x *ACPermissions) Reset() {
	*x = ACPermissions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ACPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACPermissions) ProtoMessage() {}

func (x *ACPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACPermissions.ProtoReflect.Descriptor instead.
func (*ACPermissions) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{7}
}

func (x *ACPermissions) GetForbid() []*ACPolicyStatementWrapper {
	if x != nil {
		return x.Forbid
	}
	return nil
}

func (x *ACPermissions) GetPermit() []*ACPolicyStatementWrapper {
	if x != nil {
		return x.Permit
	}
	return nil
}

type PermissionsState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Permissions *ACPermissions `protobuf:"bytes,1,opt,name=permissions,proto3" json:"permissions,omitempty"`
}

func (x *PermissionsState) Reset() {
	*x = PermissionsState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionsState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsState) ProtoMessage() {}

func (x *PermissionsState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsState.ProtoReflect.Descriptor instead.
func (*PermissionsState) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{8}
}

func (x *PermissionsState) GetPermissions() *ACPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type PermissionsStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity         *Identity         `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	PermissionsState *PermissionsState `protobuf:"bytes,2,opt,name=permissionsState,proto3" json:"permissionsState,omitempty"`
}

func (x *PermissionsStateResponse) Reset() {
	*x = PermissionsStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionsStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsStateResponse) ProtoMessage() {}

func (x *PermissionsStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsStateResponse.ProtoReflect.Descriptor instead.
func (*PermissionsStateResponse) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{9}
}

func (x *PermissionsStateResponse) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *PermissionsStateResponse) GetPermissionsState() *PermissionsState {
	if x != nil {
		return x.PermissionsState
	}
	return nil
}

type PermissionsEvaluation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Tenant   string   `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Schema   string   `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	Domain   string   `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Resource string   `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	Actions  []string `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (x *PermissionsEvaluation) Reset() {
	*x = PermissionsEvaluation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionsEvaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsEvaluation) ProtoMessage() {}

func (x *PermissionsEvaluation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsEvaluation.ProtoReflect.Descriptor instead.
func (*PermissionsEvaluation) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{10}
}

func (x *PermissionsEvaluation) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PermissionsEvaluation) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *PermissionsEvaluation) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *PermissionsEvaluation) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PermissionsEvaluation) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionsEvaluation) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

type PermissionsEvaluationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity    *Identity                `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Evaluations []*PermissionsEvaluation `protobuf:"bytes,2,rep,name=evaluations,proto3" json:"evaluations,omitempty"`
}

func (x *PermissionsEvaluationRequest) Reset() {
	*x = PermissionsEvaluationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionsEvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsEvaluationRequest) ProtoMessage() {}

func (x *PermissionsEvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsEvaluationRequest.ProtoReflect.Descriptor instead.
func (*PermissionsEvaluationRequest) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{11}
}

func (x *PermissionsEvaluationRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *PermissionsEvaluationRequest) GetEvaluations() []*PermissionsEvaluation {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

type PermissionsEvaluationOutcomeExplanation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsExplicitlyForbidden bool `protobuf:"varint,1,opt,name=isExplicitlyForbidden,proto3" json:"isExplicitlyForbidden,omitempty"`
	IsImplicitlyForbidden bool `protobuf:"varint,2,opt,name=isImplicitlyForbidden,proto3" json:"isImplicitlyForbidden,omitempty"`
}

func (x *PermissionsEvaluationOutcomeExplanation) Reset() {
	*x = PermissionsEvaluationOutcomeExplanation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionsEvaluationOutcomeExplanation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsEvaluationOutcomeExplanation) ProtoMessage() {}

func (x *PermissionsEvaluationOutcomeExplanation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsEvaluationOutcomeExplanation.ProtoReflect.Descriptor instead.
func (*PermissionsEvaluationOutcomeExplanation) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{12}
}

func (x *PermissionsEvaluationOutcomeExplanation) GetIsExplicitlyForbidden() bool {
	if x != nil {
		return x.IsExplicitlyForbidden
	}
	return false
}

func (x *PermissionsEvaluationOutcomeExplanation) GetIsImplicitlyForbidden() bool {
	if x != nil {
		return x.IsImplicitlyForbidden
	}
	return false
}

type PermissionsEvaluationOutcome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Evaluation  *PermissionsEvaluation                   `protobuf:"bytes,1,opt,name=evaluation,proto3" json:"evaluation,omitempty"`
	Permitted   bool                                     `protobuf:"varint,2,opt,name=permitted,proto3" json:"permitted,omitempty"`
	Explanation *PermissionsEvaluationOutcomeExplanation `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
}

func (x *PermissionsEvaluationOutcome) Reset() {
	*x = PermissionsEvaluationOutcome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionsEvaluationOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsEvaluationOutcome) ProtoMessage() {}

func (x *PermissionsEvaluationOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsEvaluationOutcome.ProtoReflect.Descriptor instead.
func (*PermissionsEvaluationOutcome) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{13}
}

func (x *PermissionsEvaluationOutcome) GetEvaluation() *PermissionsEvaluation {
	if x != nil {
		return x.Evaluation
	}
	return nil
}

func (x *PermissionsEvaluationOutcome) GetPermitted() bool {
	if x != nil {
		return x.Permitted
	}
	return false
}

func (x *PermissionsEvaluationOutcome) GetExplanation() *PermissionsEvaluationOutcomeExplanation {
	if x != nil {
		return x.Explanation
	}
	return nil
}

type PermissionsEvaluationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity    *Identity                       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Evaluations []*PermissionsEvaluationOutcome `protobuf:"bytes,2,rep,name=evaluations,proto3" json:"evaluations,omitempty"`
	Permitted   bool                            `protobuf:"varint,3,opt,name=permitted,proto3" json:"permitted,omitempty"`
}

func (x *PermissionsEvaluationResponse) Reset() {
	*x = PermissionsEvaluationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionsEvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsEvaluationResponse) ProtoMessage() {}

func (x *PermissionsEvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsEvaluationResponse.ProtoReflect.Descriptor instead.
func (*PermissionsEvaluationResponse) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP(), []int{14}
}

func (x *PermissionsEvaluationResponse) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *PermissionsEvaluationResponse) GetEvaluations() []*PermissionsEvaluationOutcome {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

func (x *PermissionsEvaluationResponse) GetPermitted() bool {
	if x != nil {
		return x.Permitted
	}
	return false
}

var File_internal_agents_services_pdp_endpoints_api_v1_pdp_proto protoreflect.FileDescriptor

var file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDesc = []byte{
	0x0a, 0x37, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x64, 0x70, 0x2f, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x70, 0x64, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x33,
	0x0a, 0x09, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x5c, 0x0a, 0x08, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x75, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x75,
	0x72, 0x12, 0x3e, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64, 0x65,
	0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x22, 0xa2, 0x01, 0x0a, 0x0c, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x46, 0x0a, 0x04,
	0x76, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x2e, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x69,
	0x72, 0x74, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x56, 0x69, 0x65, 0x77, 0x52, 0x04,
	0x76, 0x69, 0x65, 0x77, 0x22, 0x30, 0x0a, 0x10, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x56, 0x69, 0x65, 0x77, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x42,
	0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x55, 0x4e, 0x43, 0x4f, 0x4d, 0x42,
	0x49, 0x4e, 0x45, 0x44, 0x10, 0x01, 0x22, 0x5a, 0x0a, 0x11, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x76,
	0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x22, 0xc5, 0x01, 0x0a, 0x17, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x59,
	0x0a, 0x11, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x48, 0x00, 0x52, 0x11, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x88, 0x01, 0x01, 0x12, 0x39, 0x0a, 0x08, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x22, 0x5f, 0x0a, 0x11, 0x41, 0x43,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x18,
	0x41, 0x43, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x2e, 0x41, 0x43, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x26,
	0x0a, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x65, 0x64, 0x22, 0x9d, 0x01, 0x0a, 0x0d, 0x41, 0x43, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x45, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x62,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x41,
	0x43, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x12,
	0x45, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2d, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x41, 0x43, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x52, 0x06,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x22, 0x58, 0x0a, 0x10, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x41, 0x43, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0xa8, 0x01, 0x0a, 0x18, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a,
	0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x51, 0x0a, 0x10, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x10, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0xaf, 0x01, 0x0a, 0x15,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xa7, 0x01,
	0x0a, 0x1c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39,
	0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x4c, 0x0a, 0x0b, 0x65, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a,
	0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x65, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x95, 0x01, 0x0a, 0x27, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x15, 0x69, 0x73, 0x45, 0x78, 0x70, 0x6c, 0x69, 0x63, 0x69,
	0x74, 0x6c, 0x79, 0x46, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x15, 0x69, 0x73, 0x45, 0x78, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x6c, 0x79,
	0x46, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x12, 0x34, 0x0a, 0x15, 0x69, 0x73, 0x49,
	0x6d, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x6c, 0x79, 0x46, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x64,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x69, 0x73, 0x49, 0x6d, 0x70, 0x6c,
	0x69, 0x63, 0x69, 0x74, 0x6c, 0x79, 0x46, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x22,
	0xe8, 0x01, 0x0a, 0x1c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x45,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65,
	0x12, 0x4a, 0x0a, 0x0a, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0a, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x12, 0x5e, 0x0a, 0x0b, 0x65, 0x78,
	0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x3c, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x63, 0x6f,
	0x6d, 0x65, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x65,
	0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xcd, 0x01, 0x0a, 0x1d, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x08,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x53, 0x0a, 0x0b, 0x65, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x76,
	0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52,
	0x0b, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x32, 0x80, 0x02, 0x0a, 0x0c, 0x56,
	0x31, 0x50, 0x44, 0x50, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x72, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x2c, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2d, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x7c, 0x0a, 0x13, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x31, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x64,
	0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x44, 0x5a,
	0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x74, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x6d, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x6d, 0x69, 0x2d, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x64, 0x70,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescOnce sync.Once
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescData = file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDesc
)

func file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescGZIP() []byte {
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescOnce.Do(func() {
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescData)
	})
	return file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDescData
}

var file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_goTypes = []interface{}{
	(VirtualState_VirtualStateView)(0),              // 0: policydecisionpoint.VirtualState.VirtualStateView
	(*Attribute)(nil),                               // 1: policydecisionpoint.Attribute
	(*Identity)(nil),                                // 2: policydecisionpoint.Identity
	(*VirtualState)(nil),                            // 3: policydecisionpoint.VirtualState
	(*PermissionsEngine)(nil),                       // 4: policydecisionpoint.PermissionsEngine
	(*PermissionsStateRequest)(nil),                 // 5: policydecisionpoint.PermissionsStateRequest
	(*ACPolicyStatement)(nil),                       // 6: policydecisionpoint.ACPolicyStatement
	(*ACPolicyStatementWrapper)(nil),                // 7: policydecisionpoint.ACPolicyStatementWrapper
	(*ACPermissions)(nil),                           // 8: policydecisionpoint.ACPermissions
	(*PermissionsState)(nil),                        // 9: policydecisionpoint.PermissionsState
	(*PermissionsStateResponse)(nil),                // 10: policydecisionpoint.PermissionsStateResponse
	(*PermissionsEvaluation)(nil),                   // 11: policydecisionpoint.PermissionsEvaluation
	(*PermissionsEvaluationRequest)(nil),            // 12: policydecisionpoint.PermissionsEvaluationRequest
	(*PermissionsEvaluationOutcomeExplanation)(nil), // 13: policydecisionpoint.PermissionsEvaluationOutcomeExplanation
	(*PermissionsEvaluationOutcome)(nil),            // 14: policydecisionpoint.PermissionsEvaluationOutcome
	(*PermissionsEvaluationResponse)(nil),           // 15: policydecisionpoint.PermissionsEvaluationResponse
}
var file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_depIdxs = []int32{
	1,  // 0: policydecisionpoint.Identity.attributes:type_name -> policydecisionpoint.Attribute
	0,  // 1: policydecisionpoint.VirtualState.view:type_name -> policydecisionpoint.VirtualState.VirtualStateView
	3,  // 2: policydecisionpoint.PermissionsEngine.virtualState:type_name -> policydecisionpoint.VirtualState
	4,  // 3: policydecisionpoint.PermissionsStateRequest.permissionsEngine:type_name -> policydecisionpoint.PermissionsEngine
	2,  // 4: policydecisionpoint.PermissionsStateRequest.identity:type_name -> policydecisionpoint.Identity
	6,  // 5: policydecisionpoint.ACPolicyStatementWrapper.statement:type_name -> policydecisionpoint.ACPolicyStatement
	7,  // 6: policydecisionpoint.ACPermissions.forbid:type_name -> policydecisionpoint.ACPolicyStatementWrapper
	7,  // 7: policydecisionpoint.ACPermissions.permit:type_name -> policydecisionpoint.ACPolicyStatementWrapper
	8,  // 8: policydecisionpoint.PermissionsState.permissions:type_name -> policydecisionpoint.ACPermissions
	2,  // 9: policydecisionpoint.PermissionsStateResponse.identity:type_name -> policydecisionpoint.Identity
	9,  // 10: policydecisionpoint.PermissionsStateResponse.permissionsState:type_name -> policydecisionpoint.PermissionsState
	2,  // 11: policydecisionpoint.PermissionsEvaluationRequest.identity:type_name -> policydecisionpoint.Identity
	11, // 12: policydecisionpoint.PermissionsEvaluationRequest.evaluations:type_name -> policydecisionpoint.PermissionsEvaluation
	11, // 13: policydecisionpoint.PermissionsEvaluationOutcome.evaluation:type_name -> policydecisionpoint.PermissionsEvaluation
	13, // 14: policydecisionpoint.PermissionsEvaluationOutcome.explanation:type_name -> policydecisionpoint.PermissionsEvaluationOutcomeExplanation
	2,  // 15: policydecisionpoint.PermissionsEvaluationResponse.identity:type_name -> policydecisionpoint.Identity
	14, // 16: policydecisionpoint.PermissionsEvaluationResponse.evaluations:type_name -> policydecisionpoint.PermissionsEvaluationOutcome
	5,  // 17: policydecisionpoint.V1PDPService.GetPermissionsState:input_type -> policydecisionpoint.PermissionsStateRequest
	12, // 18: policydecisionpoint.V1PDPService.EvaluatePermissions:input_type -> policydecisionpoint.PermissionsEvaluationRequest
	10, // 19: policydecisionpoint.V1PDPService.GetPermissionsState:output_type -> policydecisionpoint.PermissionsStateResponse
	15, // 20: policydecisionpoint.V1PDPService.EvaluatePermissions:output_type -> policydecisionpoint.PermissionsEvaluationResponse
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_init() }
func file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_init() {
	if File_internal_agents_services_pdp_endpoints_api_v1_pdp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionsEngine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionsStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ACPolicyStatement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ACPolicyStatementWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ACPermissions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionsState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionsStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionsEvaluation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionsEvaluationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionsEvaluationOutcomeExplanation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionsEvaluationOutcome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionsEvaluationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_goTypes,
		DependencyIndexes: file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_depIdxs,
		EnumInfos:         file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_enumTypes,
		MessageInfos:      file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_msgTypes,
	}.Build()
	File_internal_agents_services_pdp_endpoints_api_v1_pdp_proto = out.File
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_rawDesc = nil
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_goTypes = nil
	file_internal_agents_services_pdp_endpoints_api_v1_pdp_proto_depIdxs = nil
}
