// Copyright 2024 Nitro Agility S.r.l.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/agents/services/zap/endpoints/api/v1/zap.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Zone get request.
type ZoneFetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=Page,proto3,oneof" json:"Page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,2,opt,name=PageSize,proto3,oneof" json:"PageSize,omitempty"`
	ZoneID        *int64                 `protobuf:"varint,3,opt,name=ZoneID,proto3,oneof" json:"ZoneID,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=Name,proto3,oneof" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneFetchRequest) Reset() {
	*x = ZoneFetchRequest{}
	mi := &file_internal_agents_services_zap_endpoints_api_v1_zap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneFetchRequest) ProtoMessage() {}

func (x *ZoneFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_zap_endpoints_api_v1_zap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneFetchRequest.ProtoReflect.Descriptor instead.
func (*ZoneFetchRequest) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDescGZIP(), []int{0}
}

func (x *ZoneFetchRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ZoneFetchRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ZoneFetchRequest) GetZoneID() int64 {
	if x != nil && x.ZoneID != nil {
		return *x.ZoneID
	}
	return 0
}

func (x *ZoneFetchRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// Zone create request.
type ZoneCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneCreateRequest) Reset() {
	*x = ZoneCreateRequest{}
	mi := &file_internal_agents_services_zap_endpoints_api_v1_zap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneCreateRequest) ProtoMessage() {}

func (x *ZoneCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_zap_endpoints_api_v1_zap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneCreateRequest.ProtoReflect.Descriptor instead.
func (*ZoneCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDescGZIP(), []int{1}
}

func (x *ZoneCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Zone update request.
type ZoneUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneID        int64                  `protobuf:"varint,1,opt,name=ZoneID,proto3" json:"ZoneID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneUpdateRequest) Reset() {
	*x = ZoneUpdateRequest{}
	mi := &file_internal_agents_services_zap_endpoints_api_v1_zap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneUpdateRequest) ProtoMessage() {}

func (x *ZoneUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_zap_endpoints_api_v1_zap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneUpdateRequest.ProtoReflect.Descriptor instead.
func (*ZoneUpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDescGZIP(), []int{2}
}

func (x *ZoneUpdateRequest) GetZoneID() int64 {
	if x != nil {
		return x.ZoneID
	}
	return 0
}

func (x *ZoneUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Zone delete request.
type ZoneDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneID        int64                  `protobuf:"varint,1,opt,name=ZoneID,proto3" json:"ZoneID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneDeleteRequest) Reset() {
	*x = ZoneDeleteRequest{}
	mi := &file_internal_agents_services_zap_endpoints_api_v1_zap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneDeleteRequest) ProtoMessage() {}

func (x *ZoneDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_zap_endpoints_api_v1_zap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneDeleteRequest.ProtoReflect.Descriptor instead.
func (*ZoneDeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDescGZIP(), []int{3}
}

func (x *ZoneDeleteRequest) GetZoneID() int64 {
	if x != nil {
		return x.ZoneID
	}
	return 0
}

// Zone response.
type ZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneID        int64                  `protobuf:"varint,1,opt,name=ZoneID,proto3" json:"ZoneID,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneResponse) Reset() {
	*x = ZoneResponse{}
	mi := &file_internal_agents_services_zap_endpoints_api_v1_zap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneResponse) ProtoMessage() {}

func (x *ZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_zap_endpoints_api_v1_zap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneResponse.ProtoReflect.Descriptor instead.
func (*ZoneResponse) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDescGZIP(), []int{4}
}

func (x *ZoneResponse) GetZoneID() int64 {
	if x != nil {
		return x.ZoneID
	}
	return 0
}

func (x *ZoneResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ZoneResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ZoneResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_internal_agents_services_zap_endpoints_api_v1_zap_proto protoreflect.FileDescriptor

const file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDesc = "" +
	"\n" +
	"7internal/agents/services/zap/endpoints/api/v1/zap.proto\x12\x17zoneadministrationpoint\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x01\n" +
	"\x10ZoneFetchRequest\x12\x17\n" +
	"\x04Page\x18\x01 \x01(\x05H\x00R\x04Page\x88\x01\x01\x12\x1f\n" +
	"\bPageSize\x18\x02 \x01(\x05H\x01R\bPageSize\x88\x01\x01\x12\x1b\n" +
	"\x06ZoneID\x18\x03 \x01(\x03H\x02R\x06ZoneID\x88\x01\x01\x12\x17\n" +
	"\x04Name\x18\x04 \x01(\tH\x03R\x04Name\x88\x01\x01B\a\n" +
	"\x05_PageB\v\n" +
	"\t_PageSizeB\t\n" +
	"\a_ZoneIDB\a\n" +
	"\x05_Name\"'\n" +
	"\x11ZoneCreateRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"?\n" +
	"\x11ZoneUpdateRequest\x12\x16\n" +
	"\x06ZoneID\x18\x01 \x01(\x03R\x06ZoneID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\"+\n" +
	"\x11ZoneDeleteRequest\x12\x16\n" +
	"\x06ZoneID\x18\x01 \x01(\x03R\x06ZoneID\"\xae\x01\n" +
	"\fZoneResponse\x12\x16\n" +
	"\x06ZoneID\x18\x01 \x01(\x03R\x06ZoneID\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name2\x9b\x03\n" +
	"\fV1ZAPService\x12a\n" +
	"\n" +
	"CreateZone\x12*.zoneadministrationpoint.ZoneCreateRequest\x1a%.zoneadministrationpoint.ZoneResponse\"\x00\x12a\n" +
	"\n" +
	"UpdateZone\x12*.zoneadministrationpoint.ZoneUpdateRequest\x1a%.zoneadministrationpoint.ZoneResponse\"\x00\x12a\n" +
	"\n" +
	"DeleteZone\x12*.zoneadministrationpoint.ZoneDeleteRequest\x1a%.zoneadministrationpoint.ZoneResponse\"\x00\x12b\n" +
	"\n" +
	"FetchZones\x12).zoneadministrationpoint.ZoneFetchRequest\x1a%.zoneadministrationpoint.ZoneResponse\"\x000\x01B:Z8github.com/permguard/permguard/internal/hosts/api/zap/v1b\x06proto3"

var (
	file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDescOnce sync.Once
	file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDescData []byte
)

func file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDescGZIP() []byte {
	file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDescOnce.Do(func() {
		file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDesc), len(file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDesc)))
	})
	return file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDescData
}

var file_internal_agents_services_zap_endpoints_api_v1_zap_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_agents_services_zap_endpoints_api_v1_zap_proto_goTypes = []any{
	(*ZoneFetchRequest)(nil),      // 0: zoneadministrationpoint.ZoneFetchRequest
	(*ZoneCreateRequest)(nil),     // 1: zoneadministrationpoint.ZoneCreateRequest
	(*ZoneUpdateRequest)(nil),     // 2: zoneadministrationpoint.ZoneUpdateRequest
	(*ZoneDeleteRequest)(nil),     // 3: zoneadministrationpoint.ZoneDeleteRequest
	(*ZoneResponse)(nil),          // 4: zoneadministrationpoint.ZoneResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_internal_agents_services_zap_endpoints_api_v1_zap_proto_depIdxs = []int32{
	5, // 0: zoneadministrationpoint.ZoneResponse.CreatedAt:type_name -> google.protobuf.Timestamp
	5, // 1: zoneadministrationpoint.ZoneResponse.UpdatedAt:type_name -> google.protobuf.Timestamp
	1, // 2: zoneadministrationpoint.V1ZAPService.CreateZone:input_type -> zoneadministrationpoint.ZoneCreateRequest
	2, // 3: zoneadministrationpoint.V1ZAPService.UpdateZone:input_type -> zoneadministrationpoint.ZoneUpdateRequest
	3, // 4: zoneadministrationpoint.V1ZAPService.DeleteZone:input_type -> zoneadministrationpoint.ZoneDeleteRequest
	0, // 5: zoneadministrationpoint.V1ZAPService.FetchZones:input_type -> zoneadministrationpoint.ZoneFetchRequest
	4, // 6: zoneadministrationpoint.V1ZAPService.CreateZone:output_type -> zoneadministrationpoint.ZoneResponse
	4, // 7: zoneadministrationpoint.V1ZAPService.UpdateZone:output_type -> zoneadministrationpoint.ZoneResponse
	4, // 8: zoneadministrationpoint.V1ZAPService.DeleteZone:output_type -> zoneadministrationpoint.ZoneResponse
	4, // 9: zoneadministrationpoint.V1ZAPService.FetchZones:output_type -> zoneadministrationpoint.ZoneResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_agents_services_zap_endpoints_api_v1_zap_proto_init() }
func file_internal_agents_services_zap_endpoints_api_v1_zap_proto_init() {
	if File_internal_agents_services_zap_endpoints_api_v1_zap_proto != nil {
		return
	}
	file_internal_agents_services_zap_endpoints_api_v1_zap_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDesc), len(file_internal_agents_services_zap_endpoints_api_v1_zap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_agents_services_zap_endpoints_api_v1_zap_proto_goTypes,
		DependencyIndexes: file_internal_agents_services_zap_endpoints_api_v1_zap_proto_depIdxs,
		MessageInfos:      file_internal_agents_services_zap_endpoints_api_v1_zap_proto_msgTypes,
	}.Build()
	File_internal_agents_services_zap_endpoints_api_v1_zap_proto = out.File
	file_internal_agents_services_zap_endpoints_api_v1_zap_proto_goTypes = nil
	file_internal_agents_services_zap_endpoints_api_v1_zap_proto_depIdxs = nil
}
