// Copyright 2024 Nitro Agility S.r.l.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/agents/services/pap/endpoints/api/v1/pap.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ledger get request.
type LedgerFetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=Page,proto3,oneof" json:"Page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,2,opt,name=PageSize,proto3,oneof" json:"PageSize,omitempty"`
	ZoneID        int64                  `protobuf:"varint,3,opt,name=ZoneID,proto3" json:"ZoneID,omitempty"`
	LedgerID      *string                `protobuf:"bytes,4,opt,name=LedgerID,proto3,oneof" json:"LedgerID,omitempty"`
	Kind          *string                `protobuf:"bytes,5,opt,name=Kind,proto3,oneof" json:"Kind,omitempty"`
	Name          *string                `protobuf:"bytes,6,opt,name=Name,proto3,oneof" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerFetchRequest) Reset() {
	*x = LedgerFetchRequest{}
	mi := &file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerFetchRequest) ProtoMessage() {}

func (x *LedgerFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerFetchRequest.ProtoReflect.Descriptor instead.
func (*LedgerFetchRequest) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDescGZIP(), []int{0}
}

func (x *LedgerFetchRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *LedgerFetchRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *LedgerFetchRequest) GetZoneID() int64 {
	if x != nil {
		return x.ZoneID
	}
	return 0
}

func (x *LedgerFetchRequest) GetLedgerID() string {
	if x != nil && x.LedgerID != nil {
		return *x.LedgerID
	}
	return ""
}

func (x *LedgerFetchRequest) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *LedgerFetchRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// Ledger create request.
type LedgerCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneID        int64                  `protobuf:"varint,1,opt,name=ZoneID,proto3" json:"ZoneID,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerCreateRequest) Reset() {
	*x = LedgerCreateRequest{}
	mi := &file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerCreateRequest) ProtoMessage() {}

func (x *LedgerCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerCreateRequest.ProtoReflect.Descriptor instead.
func (*LedgerCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDescGZIP(), []int{1}
}

func (x *LedgerCreateRequest) GetZoneID() int64 {
	if x != nil {
		return x.ZoneID
	}
	return 0
}

func (x *LedgerCreateRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LedgerCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Ledger update request.
type LedgerUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneID        int64                  `protobuf:"varint,1,opt,name=ZoneID,proto3" json:"ZoneID,omitempty"`
	LedgerID      string                 `protobuf:"bytes,2,opt,name=LedgerID,proto3" json:"LedgerID,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerUpdateRequest) Reset() {
	*x = LedgerUpdateRequest{}
	mi := &file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerUpdateRequest) ProtoMessage() {}

func (x *LedgerUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerUpdateRequest.ProtoReflect.Descriptor instead.
func (*LedgerUpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDescGZIP(), []int{2}
}

func (x *LedgerUpdateRequest) GetZoneID() int64 {
	if x != nil {
		return x.ZoneID
	}
	return 0
}

func (x *LedgerUpdateRequest) GetLedgerID() string {
	if x != nil {
		return x.LedgerID
	}
	return ""
}

func (x *LedgerUpdateRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LedgerUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Ledger delete request.
type LedgerDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneID        int64                  `protobuf:"varint,1,opt,name=ZoneID,proto3" json:"ZoneID,omitempty"`
	LedgerID      string                 `protobuf:"bytes,2,opt,name=LedgerID,proto3" json:"LedgerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerDeleteRequest) Reset() {
	*x = LedgerDeleteRequest{}
	mi := &file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerDeleteRequest) ProtoMessage() {}

func (x *LedgerDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerDeleteRequest.ProtoReflect.Descriptor instead.
func (*LedgerDeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDescGZIP(), []int{3}
}

func (x *LedgerDeleteRequest) GetZoneID() int64 {
	if x != nil {
		return x.ZoneID
	}
	return 0
}

func (x *LedgerDeleteRequest) GetLedgerID() string {
	if x != nil {
		return x.LedgerID
	}
	return ""
}

// Ledger response.
type LedgerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LedgerID      string                 `protobuf:"bytes,1,opt,name=LedgerID,proto3" json:"LedgerID,omitempty"`
	ZoneID        int64                  `protobuf:"varint,2,opt,name=ZoneID,proto3" json:"ZoneID,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty"`
	Ref           string                 `protobuf:"bytes,7,opt,name=Ref,proto3" json:"Ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerResponse) Reset() {
	*x = LedgerResponse{}
	mi := &file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerResponse) ProtoMessage() {}

func (x *LedgerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerResponse.ProtoReflect.Descriptor instead.
func (*LedgerResponse) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDescGZIP(), []int{4}
}

func (x *LedgerResponse) GetLedgerID() string {
	if x != nil {
		return x.LedgerID
	}
	return ""
}

func (x *LedgerResponse) GetZoneID() int64 {
	if x != nil {
		return x.ZoneID
	}
	return 0
}

func (x *LedgerResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LedgerResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *LedgerResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LedgerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LedgerResponse) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

// PackMessage is a pack message containing JSON-encoded request/response data.
type PackMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackMessage) Reset() {
	*x = PackMessage{}
	mi := &file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackMessage) ProtoMessage() {}

func (x *PackMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackMessage.ProtoReflect.Descriptor instead.
func (*PackMessage) Descriptor() ([]byte, []int) {
	return file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDescGZIP(), []int{5}
}

func (x *PackMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_agents_services_pap_endpoints_api_v1_pap_proto protoreflect.FileDescriptor

const file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDesc = "" +
	"\n" +
	"7internal/agents/services/pap/endpoints/api/v1/pap.proto\x12\x19policyadministrationpoint\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x01\n" +
	"\x12LedgerFetchRequest\x12\x17\n" +
	"\x04Page\x18\x01 \x01(\x05H\x00R\x04Page\x88\x01\x01\x12\x1f\n" +
	"\bPageSize\x18\x02 \x01(\x05H\x01R\bPageSize\x88\x01\x01\x12\x16\n" +
	"\x06ZoneID\x18\x03 \x01(\x03R\x06ZoneID\x12\x1f\n" +
	"\bLedgerID\x18\x04 \x01(\tH\x02R\bLedgerID\x88\x01\x01\x12\x17\n" +
	"\x04Kind\x18\x05 \x01(\tH\x03R\x04Kind\x88\x01\x01\x12\x17\n" +
	"\x04Name\x18\x06 \x01(\tH\x04R\x04Name\x88\x01\x01B\a\n" +
	"\x05_PageB\v\n" +
	"\t_PageSizeB\v\n" +
	"\t_LedgerIDB\a\n" +
	"\x05_KindB\a\n" +
	"\x05_Name\"U\n" +
	"\x13LedgerCreateRequest\x12\x16\n" +
	"\x06ZoneID\x18\x01 \x01(\x03R\x06ZoneID\x12\x12\n" +
	"\x04Kind\x18\x02 \x01(\tR\x04Kind\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\"q\n" +
	"\x13LedgerUpdateRequest\x12\x16\n" +
	"\x06ZoneID\x18\x01 \x01(\x03R\x06ZoneID\x12\x1a\n" +
	"\bLedgerID\x18\x02 \x01(\tR\bLedgerID\x12\x12\n" +
	"\x04Kind\x18\x03 \x01(\tR\x04Kind\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\"I\n" +
	"\x13LedgerDeleteRequest\x12\x16\n" +
	"\x06ZoneID\x18\x01 \x01(\x03R\x06ZoneID\x12\x1a\n" +
	"\bLedgerID\x18\x02 \x01(\tR\bLedgerID\"\xf2\x01\n" +
	"\x0eLedgerResponse\x12\x1a\n" +
	"\bLedgerID\x18\x01 \x01(\tR\bLedgerID\x12\x16\n" +
	"\x06ZoneID\x18\x02 \x01(\x03R\x06ZoneID\x128\n" +
	"\tCreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x12\n" +
	"\x04Kind\x18\x05 \x01(\tR\x04Kind\x12\x12\n" +
	"\x04Name\x18\x06 \x01(\tR\x04Name\x12\x10\n" +
	"\x03Ref\x18\a \x01(\tR\x03Ref\"!\n" +
	"\vPackMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xab\a\n" +
	"\fV1PAPService\x12k\n" +
	"\fCreateLedger\x12..policyadministrationpoint.LedgerCreateRequest\x1a).policyadministrationpoint.LedgerResponse\"\x00\x12k\n" +
	"\fUpdateLedger\x12..policyadministrationpoint.LedgerUpdateRequest\x1a).policyadministrationpoint.LedgerResponse\"\x00\x12k\n" +
	"\fDeleteLedger\x12..policyadministrationpoint.LedgerDeleteRequest\x1a).policyadministrationpoint.LedgerResponse\"\x00\x12l\n" +
	"\fFetchLedgers\x12-.policyadministrationpoint.LedgerFetchRequest\x1a).policyadministrationpoint.LedgerResponse\"\x000\x01\x12a\n" +
	"\rPushAdvertise\x12&.policyadministrationpoint.PackMessage\x1a&.policyadministrationpoint.PackMessage\"\x00\x12`\n" +
	"\fPushTransfer\x12&.policyadministrationpoint.PackMessage\x1a&.policyadministrationpoint.PackMessage\"\x00\x12]\n" +
	"\tPullState\x12&.policyadministrationpoint.PackMessage\x1a&.policyadministrationpoint.PackMessage\"\x00\x12a\n" +
	"\rPullNegotiate\x12&.policyadministrationpoint.PackMessage\x1a&.policyadministrationpoint.PackMessage\"\x00\x12_\n" +
	"\vPullObjects\x12&.policyadministrationpoint.PackMessage\x1a&.policyadministrationpoint.PackMessage\"\x00B:Z8github.com/permguard/permguard/internal/hosts/api/pap/v1b\x06proto3"

var (
	file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDescOnce sync.Once
	file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDescData []byte
)

func file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDescGZIP() []byte {
	file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDescOnce.Do(func() {
		file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDesc), len(file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDesc)))
	})
	return file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDescData
}

var file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_agents_services_pap_endpoints_api_v1_pap_proto_goTypes = []any{
	(*LedgerFetchRequest)(nil),    // 0: policyadministrationpoint.LedgerFetchRequest
	(*LedgerCreateRequest)(nil),   // 1: policyadministrationpoint.LedgerCreateRequest
	(*LedgerUpdateRequest)(nil),   // 2: policyadministrationpoint.LedgerUpdateRequest
	(*LedgerDeleteRequest)(nil),   // 3: policyadministrationpoint.LedgerDeleteRequest
	(*LedgerResponse)(nil),        // 4: policyadministrationpoint.LedgerResponse
	(*PackMessage)(nil),           // 5: policyadministrationpoint.PackMessage
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_internal_agents_services_pap_endpoints_api_v1_pap_proto_depIdxs = []int32{
	6,  // 0: policyadministrationpoint.LedgerResponse.CreatedAt:type_name -> google.protobuf.Timestamp
	6,  // 1: policyadministrationpoint.LedgerResponse.UpdatedAt:type_name -> google.protobuf.Timestamp
	1,  // 2: policyadministrationpoint.V1PAPService.CreateLedger:input_type -> policyadministrationpoint.LedgerCreateRequest
	2,  // 3: policyadministrationpoint.V1PAPService.UpdateLedger:input_type -> policyadministrationpoint.LedgerUpdateRequest
	3,  // 4: policyadministrationpoint.V1PAPService.DeleteLedger:input_type -> policyadministrationpoint.LedgerDeleteRequest
	0,  // 5: policyadministrationpoint.V1PAPService.FetchLedgers:input_type -> policyadministrationpoint.LedgerFetchRequest
	5,  // 6: policyadministrationpoint.V1PAPService.PushAdvertise:input_type -> policyadministrationpoint.PackMessage
	5,  // 7: policyadministrationpoint.V1PAPService.PushTransfer:input_type -> policyadministrationpoint.PackMessage
	5,  // 8: policyadministrationpoint.V1PAPService.PullState:input_type -> policyadministrationpoint.PackMessage
	5,  // 9: policyadministrationpoint.V1PAPService.PullNegotiate:input_type -> policyadministrationpoint.PackMessage
	5,  // 10: policyadministrationpoint.V1PAPService.PullObjects:input_type -> policyadministrationpoint.PackMessage
	4,  // 11: policyadministrationpoint.V1PAPService.CreateLedger:output_type -> policyadministrationpoint.LedgerResponse
	4,  // 12: policyadministrationpoint.V1PAPService.UpdateLedger:output_type -> policyadministrationpoint.LedgerResponse
	4,  // 13: policyadministrationpoint.V1PAPService.DeleteLedger:output_type -> policyadministrationpoint.LedgerResponse
	4,  // 14: policyadministrationpoint.V1PAPService.FetchLedgers:output_type -> policyadministrationpoint.LedgerResponse
	5,  // 15: policyadministrationpoint.V1PAPService.PushAdvertise:output_type -> policyadministrationpoint.PackMessage
	5,  // 16: policyadministrationpoint.V1PAPService.PushTransfer:output_type -> policyadministrationpoint.PackMessage
	5,  // 17: policyadministrationpoint.V1PAPService.PullState:output_type -> policyadministrationpoint.PackMessage
	5,  // 18: policyadministrationpoint.V1PAPService.PullNegotiate:output_type -> policyadministrationpoint.PackMessage
	5,  // 19: policyadministrationpoint.V1PAPService.PullObjects:output_type -> policyadministrationpoint.PackMessage
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_agents_services_pap_endpoints_api_v1_pap_proto_init() }
func file_internal_agents_services_pap_endpoints_api_v1_pap_proto_init() {
	if File_internal_agents_services_pap_endpoints_api_v1_pap_proto != nil {
		return
	}
	file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDesc), len(file_internal_agents_services_pap_endpoints_api_v1_pap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_agents_services_pap_endpoints_api_v1_pap_proto_goTypes,
		DependencyIndexes: file_internal_agents_services_pap_endpoints_api_v1_pap_proto_depIdxs,
		MessageInfos:      file_internal_agents_services_pap_endpoints_api_v1_pap_proto_msgTypes,
	}.Build()
	File_internal_agents_services_pap_endpoints_api_v1_pap_proto = out.File
	file_internal_agents_services_pap_endpoints_api_v1_pap_proto_goTypes = nil
	file_internal_agents_services_pap_endpoints_api_v1_pap_proto_depIdxs = nil
}
