// Copyright (c) 2022 Nitro Agility S.r.l.
// SPDX-License-Identifier: Apache-2.0

//! RFC 8785 numbers, against vectors that do not come from this code.
//!
//! Appendix B of RFC 8785 lists IEEE-754 values and the text ECMAScript's `Number.prototype.toString`
//! gives them, which is the canonical form. `tests/fixtures/jcs-numbers.txt` extends it with 3 368
//! more values, generated by Node from a fixed seed: the reference implementation of the very
//! function RFC 8785 cites. Each value must canonicalise to its stated text, and that text must
//! read back to the same bits and pass the byte-identity check.

#![allow(clippy::expect_used)]

use permguard_stream::jcs::{canonicalize, decode_canonical, parse_strict};
use serde_json::Value;

/// RFC 8785 Appendix B, less the two non-finite rows, which no JSON value can hold.
const APPENDIX_B: [(u64, &str); 24] = [
    (0x0000000000000000, "0"),
    (0x8000000000000000, "0"),
    (0x0000000000000001, "5e-324"),
    (0x8000000000000001, "-5e-324"),
    (0x7fefffffffffffff, "1.7976931348623157e+308"),
    (0xffefffffffffffff, "-1.7976931348623157e+308"),
    (0x4340000000000000, "9007199254740992"),
    (0xc340000000000000, "-9007199254740992"),
    (0x4430000000000000, "295147905179352830000"),
    (0x44b52d02c7e14af5, "9.999999999999997e+22"),
    (0x44b52d02c7e14af6, "1e+23"),
    (0x44b52d02c7e14af7, "1.0000000000000001e+23"),
    (0x444b1ae4d6e2ef4e, "999999999999999700000"),
    (0x444b1ae4d6e2ef4f, "999999999999999900000"),
    (0x444b1ae4d6e2ef50, "1e+21"),
    (0x3eb0c6f7a0b5ed8c, "9.999999999999997e-7"),
    (0x3eb0c6f7a0b5ed8d, "0.000001"),
    (0x41b3de4355555553, "333333333.3333332"),
    (0x41b3de4355555554, "333333333.33333325"),
    (0x41b3de4355555555, "333333333.3333333"),
    (0x41b3de4355555556, "333333333.3333334"),
    (0x41b3de4355555557, "333333333.33333343"),
    (0xbecbf647612f3696, "-0.0000033333333333333333"),
    (0x43143ff3c1cb0959, "1424953923781206.2"),
];

fn check(bits: u64, expected: &str) {
    let number = f64::from_bits(bits);
    let value = Value::from(number);
    let canonical = canonicalize(&value)
        .unwrap_or_else(|error| panic!("{bits:016x} ({number:e}) was refused: {error}"));
    assert_eq!(
        String::from_utf8(canonical.clone()).expect("UTF-8"),
        expected,
        "{bits:016x}"
    );

    let read = parse_strict(expected.as_bytes())
        .unwrap_or_else(|error| panic!("`{expected}` was refused on read: {error}"));
    let read_back = read.as_f64().expect("a number");
    // Negative zero is written as `0`, which reads back as positive zero: equal as numbers.
    assert!(
        read_back == number && (number != 0.0 || read_back == 0.0),
        "`{expected}` read back as {read_back:e}, not {number:e}"
    );
    decode_canonical(&canonical)
        .unwrap_or_else(|error| panic!("`{expected}` failed byte identity: {error}"));
}

#[test]
fn test_rfc8785_appendix_b() {
    for (bits, expected) in APPENDIX_B {
        check(bits, expected);
    }
}

#[test]
fn test_every_number_the_node_oracle_printed() {
    let fixture = include_str!("fixtures/jcs-numbers.txt");
    let mut checked = 0;
    for line in fixture.lines().filter(|line| !line.starts_with('#')) {
        let (hex, expected) = line.split_once(' ').expect("`<hex> <text>`");
        check(u64::from_str_radix(hex, 16).expect("hex bits"), expected);
        checked += 1;
    }
    assert_eq!(checked, 3_366, "the whole fixture was read");
}
