# .github/workflows/release.yml
name: permguard-release

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access
  attestations: write # needed for provenance

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # this is important, otherwise it won't checkout the full tree (i.e. no previous tags)
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: sigstore/cosign-installer@v3.10.0 # installs cosign
      - uses: anchore/sbom-action/download-syft@v0.20.6 # installs syft
      # - uses: docker/login-action@v3 # login to ghcr
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v6 # run goreleaser
        with:
          distribution: goreleaser-pro
          version: "latest"
          args: release --clean --config .goreleaser-pro.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      # - uses: actions/attest-build-provenance@v3
      #   with:
      #     subject-checksums: ./dist/checksums.txt
      # - uses: actions/attest-build-provenance@v3
      #   with:
      #     subject-checksums: ./dist/digests.txt
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #     GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
